package bo.afcoop.rec.dto;
// Generated 19-10-2016 06:28:50 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * AdmEnlace generated by hbm2java
 */
public class AdmEnlace  implements java.io.Serializable {


     private Integer idAdmEnlace;
     private Integer idAdmModulo;
     private String descripcion;
     private Integer insertBy;
     private Integer updateBy;
     private Date insertTime;
     private Date updateTime;
     private Integer estado;
     private List<AdmMenu> admMenus;

    public AdmEnlace() {
    }
   
    public Integer getIdAdmEnlace() {
        return this.idAdmEnlace;
    }

    public Integer getAdmModuloId() {
        return idAdmModulo;
    }

    public void setAdmModuloId(Integer idAdmModulo) {
        this.idAdmModulo = idAdmModulo;
    }
    
    public void setIdAdmEnlace(Integer idAdmEnlace) {
        this.idAdmEnlace = idAdmEnlace;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
   
    public Integer getInsertBy() {
        return this.insertBy;
    }
    
    public void setInsertBy(Integer insertBy) {
        this.insertBy = insertBy;
    }
    public Integer getUpdateBy() {
        return this.updateBy;
    }
    
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }
    public Date getInsertTime() {
        return this.insertTime;
    }
    
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }

    public List<AdmMenu> getAdmMenus() {
        return admMenus;
    }

    public void setAdmMenus(List<AdmMenu> admMenus) {
        this.admMenus = admMenus;
    }

    
}


