package bo.afcoop.rec.dto;
// Generated 19-10-2016 06:28:50 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AdmMenu generated by hbm2java
 */
public class AdmMenu  implements java.io.Serializable {


     private int idAdmMenu;
     private String descripcion;
     private String url;
     private int insertBy;
     private int updateBy;
     private Date insertTime;
     private Date updateTime;
     private Integer estado;
     private Set admEnlaceMenus = new HashSet(0);

    public AdmMenu() {
    }

	
    public AdmMenu(int idAdmMenu, int insertBy, int updateBy, Date insertTime) {
        this.idAdmMenu = idAdmMenu;
        this.insertBy = insertBy;
        this.updateBy = updateBy;
        this.insertTime = insertTime;
    }
    public AdmMenu(int idAdmMenu, String descripcion, String url, int insertBy, int updateBy, Date insertTime, Date updateTime, Integer estado, Set admEnlaceMenus) {
       this.idAdmMenu = idAdmMenu;
       this.descripcion = descripcion;
       this.url = url;
       this.insertBy = insertBy;
       this.updateBy = updateBy;
       this.insertTime = insertTime;
       this.updateTime = updateTime;
       this.estado = estado;
       this.admEnlaceMenus = admEnlaceMenus;
    }
   
    public int getIdAdmMenu() {
        return this.idAdmMenu;
    }
    
    public void setIdAdmMenu(int idAdmMenu) {
        this.idAdmMenu = idAdmMenu;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public int getInsertBy() {
        return this.insertBy;
    }
    
    public void setInsertBy(int insertBy) {
        this.insertBy = insertBy;
    }
    public int getUpdateBy() {
        return this.updateBy;
    }
    
    public void setUpdateBy(int updateBy) {
        this.updateBy = updateBy;
    }
    public Date getInsertTime() {
        return this.insertTime;
    }
    
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public Set getAdmEnlaceMenus() {
        return this.admEnlaceMenus;
    }
    
    public void setAdmEnlaceMenus(Set admEnlaceMenus) {
        this.admEnlaceMenus = admEnlaceMenus;
    }




}


