package bo.afcoop.rec.dto;
// Generated 19-10-2016 06:28:50 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * AdmModulo generated by hbm2java
 */
public class AdmModulo  implements java.io.Serializable {

    

     private Integer idAdmModulo;
     private String descripcion;
     private Integer insertBy;
     private Integer updateBy;
     private Date insertTime;
     private Date updateTime;
     private Integer estado;
     private List<AdmEnlace> admEnlaces;

    public AdmModulo() {
    }
    
    public Integer getIdAdmModulo() {
        return this.idAdmModulo;
    }
    
    public void setIdAdmModulo(Integer idAdmModulo) {
        this.idAdmModulo = idAdmModulo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    public Integer getInsertBy() {
        return this.insertBy;
    }
    
    public void setInsertBy(Integer insertBy) {
        this.insertBy = insertBy;
    }
    public Integer getUpdateBy() {
        return this.updateBy;
    }
    
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }
    public Date getInsertTime() {
        return this.insertTime;
    }
    
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }

    public List<AdmEnlace> getAdmEnlaces() {
        return admEnlaces;
    }

    public void setAdmEnlaces(List<AdmEnlace> admEnlaces) {
        this.admEnlaces = admEnlaces;
    }
}


