package bo.afcoop.rec.dto;
// Generated 19-10-2016 06:28:50 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AdmUsuario generated by hbm2java
 */
public class RegCooperativa implements java.io.Serializable {

    private Long idCooperativa;
    private String nroRegistro;
    private String denominacion;
    private String razonSocial;
    private Date fecFundacion;
    private Date fecRegSirenco;
    private String observacion;
    private Long idUsuarioRegistro;
    private Long idUsuarioModificacion;
    private Date fecRegistro;
    private Date fecModificacion;
    private Integer estado;

    public RegCooperativa() {
    }

    public Long getIdCooperativa() {
        return idCooperativa;
    }

    public void setIdCooperativa(Long idCooperativa) {
        this.idCooperativa = idCooperativa;
    }

    public String getNroRegistro() {
        return nroRegistro;
    }

    public void setNroRegistro(String nroRegistro) {
        this.nroRegistro = nroRegistro;
    }

    public String getDenominacion() {
        return denominacion;
    }

    public void setDenominacion(String denominacion) {
        this.denominacion = denominacion;
    }

    public String getRazonSocial() {
        return razonSocial;
    }

    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }

    public Date getFecFundacion() {
        return fecFundacion;
    }

    public void setFecFundacion(Date fecFundacion) {
        this.fecFundacion = fecFundacion;
    }

    public Date getFecRegSirenco() {
        return fecRegSirenco;
    }

    public void setFecRegSirenco(Date fecRegSirenco) {
        this.fecRegSirenco = fecRegSirenco;
    }

    public String getObservacion() {
        return observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    public Long getIdUsuarioRegistro() {
        return idUsuarioRegistro;
    }

    public void setIdUsuarioRegistro(Long idUsuarioRegistro) {
        this.idUsuarioRegistro = idUsuarioRegistro;
    }

    public Long getIdUsuarioModificacion() {
        return idUsuarioModificacion;
    }

    public void setIdUsuarioModificacion(Long idUsuarioModificacion) {
        this.idUsuarioModificacion = idUsuarioModificacion;
    }

    public Date getFecRegistro() {
        return fecRegistro;
    }

    public void setFecRegistro(Date fecRegistro) {
        this.fecRegistro = fecRegistro;
    }

    public Date getFecModificacion() {
        return fecModificacion;
    }

    public void setFecModificacion(Date fecModificacion) {
        this.fecModificacion = fecModificacion;
    }

    public Integer getEstado() {
        return estado;
    }

    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    
    
    

}
